### ISSUE TITLE
Fail to import `../../package.json` on Vercel with pnpm

### ISSUE THREAD

**Issue by grod** [adobe/fetch#482]
**Description**
I'm using `@adobe/helix-md2docx` which depends on `@adobe/fetch`

I'm using pnpm and when I deploy to Vercel I'm getting the following error:

```
Error: Cannot find module '../../package.json'
Require stack:
- /vercel/path0/node_modules/.pnpm/@adobe+fetch@4.1.8/node_modules/@adobe/fetch/src/core/request.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at /var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.0_@opentelemetry+api@1.9.0_@playwright+test@1.45.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:90905
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at /opt/rust/nodejs.js:1:11508
    at Function.Wt (/opt/rust/nodejs.js:1:11878)
    at Q.e.<computed>.K._load (/opt/rust/nodejs.js:1:11478)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at h.require (/var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.0_@opentelemetry+api@1.9.0_@playwright+test@1.45.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:91121)
    at require (node:internal/modules/helpers:177:18)
    at 6141 (/var/task/apps/app/.next/server/app/api/reports/[id]/export/route.js:7:12225) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/vercel/path0/node_modules/.pnpm/@adobe+fetch@4.1.8/node_modules/@adobe/fetch/src/core/request.js'
  ],
  page: '/api/reports/49a10492-e00e-4056-b6e3-905daa070db0/export'
}
```

This is caused by this line:
https://github.com/adobe/fetch/blob/11eaa8483f8df8a0da986152bb9b8c82489240c6/src/core/request.js#L29

**Version:**
4.1.8

**Additional context**
This works locally, but fails on Vercel

**Comment by stefan-guggisberg** [comment]
Thanks for reporting this issue. `adobe/fetch` does neither specifically target pnpm nor Vercel. Any related issues with these environments are out of the scope of this project.
